### ISSUE TITLE
better error message when truncating past max seq length

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-dada2#16]
When passing `--p-trunc-len` with a length greater than the length of the input sequences, `dada2 denoise` (which runs `run_data.R`) fails with an uninformative error message. For example, running this command (`--p-trunc-len 98`) on sequences that have 90 positions:

``` shell
$ qiime dada2 denoise --i-demultiplexed-seqs 88soils-tutorial-demux-1p.qza --o-representative-sequences rep-seqs --o-table table --p-trim-left 0 --p-trunc-len 98 --verbose
Running external command line application(s). This may print messages to stdout and/or stderr.
The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

Command: run_dada.R /var/folders/h3/2l54lt8d69db92g2mlsc_wnw0000gp/T/qiime2-archive-tg33bd_3/52802aaa-e515-4eb6-a193-4466da154458/data /var/folders/h3/2l54lt8d69db92g2mlsc_wnw0000gp/T/tmp83ajfcmt/output.tsv.biom 98 0 /var/folders/h3/2l54lt8d69db92g2mlsc_wnw0000gp/T/tmp83ajfcmt

Loading required package: Rcpp
There were 50 or more warnings (use warnings() to see the first 50)
Initial error matrix unspecified. Error rates will be initialized to the maximum possible estimate from this data.
Error in colSums(trans[paste0(nti, "2", c("A", "C", "G", "T")), ]) :
  'x' must be an array of at least two dimensions
Calls: dada -> errorEstimationFunction -> colSums
Execution halted
Traceback (most recent call last):
  File "/Users/jairideout/miniconda3/envs/qiime2-test/bin/qiime", line 6, in <module>
    sys.exit(q2cli.__main__.qiime())
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/site-packages/q2cli-0.0.5-py3.5.egg/q2cli/commands.py", line 210, in __call__
  File "<decorator-gen-131>", line 2, in denoise
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/site-packages/qiime-2.0.5-py3.5.egg/qiime/core/callable.py", line 221, in callable_wrapper
    output_types)
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/site-packages/qiime-2.0.5-py3.5.egg/qiime/core/callable.py", line 321, in _callable_executor_
    output_views = callable(**view_args)
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/site-packages/q2_dada2-0.0.5-py3.5.egg/q2_dada2/_denoise.py", line 29, in denoise
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/site-packages/q2_dada2-0.0.5-py3.5.egg/q2_dada2/_plot.py", line 29, in run_commands
  File "/Users/jairideout/miniconda3/envs/qiime2-test/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['run_dada.R', '/var/folders/h3/2l54lt8d69db92g2mlsc_wnw0000gp/T/qiime2-archive-tg33bd_3/52802aaa-e515-4eb6-a193-4466da154458/data', '/var/folders/h3/2l54lt8d69db92g2mlsc_wnw0000gp/T/tmp83ajfcmt/output.tsv.biom', '98', '0', '/var/folders/h3/2l54lt8d69db92g2mlsc_wnw0000gp/T/tmp83ajfcmt']' returned non-zero exit status 1
```

It would be helpful to have a more informative error message. Not sure if this should happen in the R dada2 library itself or in q2-dada2.

**Comment by jairideout** [comment]
This is no longer an issue, thanks @ebolyen!
