### ISSUE TITLE
BUG:Can not run qiime dada2 denoise-ccs without primers or adapters 

### ISSUE THREAD

**Issue by cherman2** [qiime2/q2-dada2#163]
**Improvement Description**
We need to be able to run qiime dada2 denoise-ccs even if the data does not have primers or adapters. some users are receiving their data from sequencers without adapters, primers, and the sequences and merged 

**Current Behavior**
qiime dada2 denoise-ccs requires   --p-front and --p-adapter are required fields. Looking at the code, I believe this is something we are enforcing on the qiime2 interface side and it does not seem to be a requirement of dada2.

**Proposed Behavior**
Users on the forum have said that they are receiving data without primers and adapters and therefore can not run denoise-ccs

**Comments**
1. users does note that many sequences are not being classified because the sequences are reverse compliment. 

**References**
1. [ Forum X-Ref](https://forum.qiime2.org/t/qiime-dada2-denoise-ccs-without-primers-or-adapters/28546)

**Comment by lizgehret** [comment]
I haven't looked at this in detail, but offhand this seems like a good one for you to work on @hagenjp - this should just be modifying the `--p-front` and `--p-adapter` fields to not be required on the QIIME 2 side. Assigning this to you in case you want a break from all of your migration work, but no immediate rush on this!

**Comment by yongmingwang12syp** [comment]
I had the same problem, but what puzzled me was why someone could run the code without writing those two parameters.

**Comment by lida56** [comment]
Hi, 
I am the first time user of Qiime and found this conversation as I too have problem using "qiime dada2 denoise-ccs". Here is the script I used 
qiime dada2 denoise-ccs --i-demultiplexed-seqs ${dir}/demultiplexed-trimmed-single.qza --p-trim-left 20 --p-trunc-len 1600 --p-n-threads 20 --o-representative-sequences ${dir}/rep-seqs-dada2.qza --o-table ${dir}/table-dada-test1.qza --o-denoising-stats ${dir}/stats-dada2-test1.qza --p-front AGRGTTYGATYMTGGCTCAG --p-adapter AAGTCGTAACAAGGTARCY --verbose

And the error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sw/auto/rocky8c/epyc4/software/QIIME2/2022.8/lib/python3.8/site-packages/q2cli/commands.py", line 339, in __call__
    results = action(**arguments)
  File "<decorator-gen-402>", line 2, in denoise_ccs
  File "/sw/auto/rocky8c/epyc4/software/QIIME2/2022.8/lib/python3.8/site-packages/qiime2/sdk/action.py", line 234, in bound_callable
    outputs = self._callable_executor_(scope, callable_args,
  File "/sw/auto/rocky8c/epyc4/software/QIIME2/2022.8/lib/python3.8/site-packages/qiime2/sdk/action.py", line 381, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/sw/auto/rocky8c/epyc4/software/QIIME2/2022.8/lib/python3.8/site-packages/q2_dada2/_denoise.py", line 419, in denoise_ccs
    raise Exception("An error was encountered while running DADA2"
Exception: An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

Plugin error from dada2:

  An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

See above for debug info.

Thanks in advance for your help
Lida

**Comment by gregcaporaso** [comment]
Hi @lida56, I'm not sure that this is related to this specific GitHub issue. Would you mind posting this with a request for help on the [QIIME 2 Forum](https://forum.qiime2.org)? We can help you troubleshoot this there.

**Comment by colinvwood** [comment]
closed by #168

**Comment by colinvwood** [comment]
Reopening because we need to also support situations where both the forward and reverse primers have been removed. See [here](https://forum.qiime2.org/t/pacbio-16s-data-nextflow-error-while-using-a-cluster/31312) for an example.

**Comment by colinvwood** [comment]
Waiting on #169 and then #172.

**Comment by colinvwood** [comment]
another request for this [here](https://forum.qiime2.org/t/16s-ccs-without-primers-how-to-skip-p-front-p-adapter-in-denoise-ccs/33621)

**Comment by gregcaporaso** [comment]
Another forum xref here: https://forum.qiime2.org/t/request-dada2-denoise-ccs-without-p-front-parameter/34277
